export const mockUserCase1 = {
  id: '',
  state: 'FIS',
  namedApplicant: true,
  saveAndContinue: 'true',
  applicantDateOfBirth: { year: '1829', month: '12', day: '27' },
  applicantAddressPostcode: 'G11 XXL',
  applicantSelectAddress: '10',
  applicantAddress1: '100 Dummy Avenue',
  applicantAddress2: '',
  applicantAddressTown: 'DummyCity',
  applicantAddressCounty: 'CITY OF Dummy',
  contactPreferenceType: 'ACCOUNT_OWNER',
  emailAddress: 'dummy@bob.com',
  homePhoneNumber: '012345678910',
  mobilePhoneNumber: '012345678910',
  applicantFirstNames: 'Joe',
  applicantLastNames: 'Bob',
} as unknown as any;

export const mockUserCase2 = {
  id: '',
  state: 'FIS',
  namedApplicant: true,
  saveAndContinue: 'true',
  applicantDateOfBirth: { year: '1829', month: '12', day: '27' },
  applicantAddressPostcode: 'G11 XXL',
  applicantSelectAddress: '10',
  applicantAddress1: '100 Dummy Avenue',
  applicantAddress2: '',
  applicantAddressTown: 'DummyCity',
  applicantAddressCounty: 'CITY OF Dummy',
  contactPreferenceType: 'NAMED_PERSON',
  emailAddress: 'dummy@bob.com',
  homePhoneNumber: '012345678910',
  mobilePhoneNumber: '012345678910',
  applicantFirstNames: 'Foe',
  applicantLastNames: 'Bob',
} as unknown as any;

export const mockUserCase3 = {
  id: '',
  state: 'FIS',
  namedApplicant: true,
  saveAndContinue: 'true',
  applicantDateOfBirth: { year: '1829', month: '12', day: '27' },
  applicantAddressPostcode: 'G11 XXL',
  applicantSelectAddress: '10',
  applicantAddress1: '100 Dummy Avenue',
  applicantAddress2: '',
  applicantAddressTown: 'DummyCity',
  applicantAddressCounty: 'CITY OF Dummy',
  contactPreferenceType: 'BOTH_RECEIVE',
  emailAddress: 'dummy@bob.com',
  homePhoneNumber: '012345678910',
  mobilePhoneNumber: '012345678910',
  applicantFirstNames: 'Foe',
  applicantLastNames: 'Bob',
} as unknown as any;
